# Generated by Django 4.2.12 on 2024-05-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sale_profit_sparepart_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
